var items = [{sec: "resp_items", img: "tuba.jpg", alt: "Un tuba.", name: "Tuba", desc: "Ventilation pour plongée en eaux peu profondes.", ppu: "3"},
             {sec: "resp_items", img: "detendeur.jpg", alt: "Un ensemble détendeur de plongée avec tuyauterie.", name: "Détendeur de plongée", desc: "Pour la plongée en scaphandre. Système complet contenant la tuyauterie, un détendeur de stade un et deux détendeurs de stade deux, ainsi qu'une jauge de pression.", ppu: "30"},
             {sec: "resp_items", img: "bonbonne_air.jpg", alt: "Une bonbonne d'air.", name: "Bonbonne d'air comprimé", desc: "Pour la plongée en scaphandre. Recommandé pour les plongeurs néophytes. Vient avec remplissage illimité.", ppu: "20"},
             {sec: "resp_items", img: "nitrox.jpg", alt: "Étiquette d'une bonbonne de nitrox.", name: "Bonbonne de nitrox", desc: "Pour la plongée en scaphandre. Air réduit en azote, pour une plongée en scaphandre plus sécuritaire en profondeur. Vient avec remplissage illimité.<strong>Requiert une formation avant utilisation.</strong>", ppu: "30"},
             {sec: "resp_items", img: "recirculation.png", alt: "Un système de recirculation.", name: "Système de recirculation", desc: "Pour la plongée en scaphandre de durée prolongée. Réutilise le gaz expiré de façon à diminuer la consommation d'air comprimé.", ppu: "70"},

             {sec: "prot_items", img: "wetsuit.jpg", alt: "Un wetsuit.", name: "Wetsuit", desc: "Protection du tronc, des bras et des jambes pour la plongée en scaphandre, en apnée ou avec tuba.", ppu: "15"},
             {sec: "prot_items", img: "cagoule.jpg", alt: "Une cagoule de plongée.", name: "Cagoule", desc: "Protection de la tête pour la plongée en scaphandre, en apnée ou avec tuba.", ppu: "3"},
             {sec: "prot_items", img: "masque.jpg", alt: "Un masque de plongée.", name: "Masque de plongée", desc: "Essentiel à tous types de plongée. Pour la visibilité et la protection des yeux.", ppu: "3"},
             {sec: "prot_items", img: "gants.jpg", alt: "Des gants de plongée.", name: "Gants", desc: "Protection des mains pour la plongée en scaphandre, en apnée ou avec tuba.", ppu: "3"},
             {sec: "prot_items", img: "bottes.jpg", alt: "Des bottes de plongée.", name: "Bottes", desc: "Protection des pieds et sécurisation des palmes pour la plongée en scaphandre, en apnée ou avec tuba.", ppu: "5"},
             {sec: "prot_items", img: "palmes.jpg", alt: "Des palmes de plongée.", name: "Palmes", desc: "Aide à la propulsion pour la plongée en scaphandre, en apnée ou avec tuba.", ppu: "5"},
             {sec: "prot_items", img: "atmosuit.jpg", alt: "Un habit atmosphérique.", name: "Habit atmosphérique", desc: "Habit pour la plongée en profondeur. Protection intégrale du corps et pression interne contrôlée.<strong>Requiert une formation avant utilisation.</strong>", ppu: "150"},

             {sec: "accs_items", img: "ordi_plongee.jpg", alt: "Un ordinateur de plongée.", name: "Ordinateur de plongée", desc: "Permet d'optimiser le temps de plongée en calculant le temps à passer dans différents palliers de décompression.", ppu: "30"},
             {sec: "accs_items", img: "sac_plongee.jpg", alt: "Un sac de plongée.", name: "Sac d'équipement de plongée", desc: "Pour entreposer l'équipement de plongée", ppu: "10"},
             {sec: "accs_items", img: "ceinture_lestage.jpg", alt: "Une ceinture de lestage.", name: "Ceinture de lestage", desc: "Pour stabiliser la profondeur du plongeur et accélérer la descente. Vient avec 10kg de lest.", ppu: "5"},
             {sec: "accs_items", img: "gilet_stabilisateur.jpg", alt: "Un gilet stabilisateur.", name: "Gilet stabilisateur", desc: "Pour stabiliser la profondeur du plongeur et accélérer la remontée.", ppu: "20"},
             {sec: "accs_items", img: "camera_plongee.png", alt: "Une plongeuse portant une caméra de plongée.", name: "Caméra deplongée", desc: "Pour enregistrer tous vos exploits.", ppu: "30"},

             {sec: "forf_items", img: "forf_tuba.jpg", alt: "L'équipement fourni par le forfait de plongée en apnée.", name: "Forfait plongée en apnée", desc: "Inclut: wetsuit, gants, bottes, masque de plongée, tuba et palmes", ppu: "30"},
             {sec: "forf_items", img: "forf_scaphandre.jpg", alt: "L'équipement fourni par le forfait de plongée en scaphandre.", name: "Forfait plongée en scaphandre", desc: "Inclut : wetsuit, bottes, palmes, tuba, masque de plongée, détendeur de plongée, bonbonnes d'air comprimé, ceinture de lestage, gilet stabilisateur et ordinateur de plongée.", ppu: "110"},
             {sec: "forf_items", img: "forf_profondeur.jpg", alt: "L'équipement fourni par le forfait de plongée en profondeur.", name: "Forfait plongée en profondeur", desc: "Inclut : habit atmosphérique et tuyauterie. Du personnel qualifié s'occupera de gérer l'équipement durant la plongée.", ppu: "300"}];